### PR TITLE
fix: update the sonarcloud project key in `build.gradle.kts`

### PR DESCRIPTION
**Pull request by charliemangano**
### Description:
This PR lets SonarCloud be integrated in GitHubActions by having the correct key in our build file.

#### **Key Changes:**
- Updated `sonar.projectKey` from `PeriodPals_periodpals` to `periodpals_periodpals` to match the name of the reinitialised project on SonarCloud

### CODE REVIEW

**Comment by agonzalez-r** [comment]
LGTM

**Review by agonzalez-r — DISMISSED** [review]
LGTM

**Review by francelu — COMMENTED** [review]
Most of the modifications seem to be related to code formatting, likely due to ktfmt. The changes look good to me!  
Please ensure that CI checks pass before merging.

**Comment by charliemangano** [comment]
Will be fixed by #27 , closing this PR.

**Pull request closed without merging**
