### PR TITLE
Feat/alert/list screen: Finish UI for the list of alerts

### PR DESCRIPTION
**Pull request by lazarinibruno**
## Overview
This PR introduces a new screen called `AlertListScreen`. The goal of this screen is to list the alerts posted both by the user (`My Alerts`)  and other users (`Pals Alerts`).

image

## Key Changes and Features

* To navigate between `My Alerts` and `Pals Alerts`, I implemented a `TabRow`. 
* Each alert corresponds to a `Card` which contains the most important information. This includes: profile picture, name, location, time, menstrual product type and urgency level.
* Whenever there aren't any alerts, a message is displayed indicating it.

## Future Improvements

* For the moment, I used placeholder values for the items in the list. Next sprint (S2), @agonzalez-r and I will finish the Model and ViewModel for the alert list (see #17). This will allow us to replace the placeholder values for actual data coming from the database.
* Once the ViewModel is implemented, I will replace the `Column` in the screen by a `LazyColumn` which is more efficient and will allow the user to scroll.
* I would also like to add an "Organize by" feature, that allows the user to sort the alerts in function of the urgency, location, time and proximity.
* The icons for the profile pic, the menstrual product type and for the urgency level are placeholder also ones. Next sprint I will design the corresponding icons (see #22).

## Tests

* I wrote tests to ensure that all of the composables are correctly displayed and that the switching between tab works properly.

### CODE REVIEW

**Review by agonzalez-r — APPROVED** [review]
## Important
- `AlertList.kt` should be under `app/src/main/java/com/android/periodpals/ui/alert` (the same folder as `AlertScreen` and the upcoming screens like `EditAlertScreen`)

## Improvements
- Instead of explaining in a comment that `(0 -> MyAlerts; 1 -> PalsAlerts)`, I think there can be a list with the name of the tabs and you can iterate over the indexes of that list. [See this example](https://composables.com/material3/tabrow).

## Overall Comments 
- I really like the UI !
- Clean code, properly formatted and good comments that make the code easy to read
- Tests are very complete

**Review by charliemangano — APPROVED** [review]
I really like the tabbing system, and it looks great!

### Comments
 - Sonarcloud is not correctly configured (see #26), you actually have 100% line coverage:) It's great, thank you for your work!
 - As mentionned by @agonzalez-r, fix the files' location:
   - `AlertsList.kt` should be in `app/src/main/java/com/android/periodpals/ui/alert`
   - `AlertsListScreenTest.kt` should be in `app/src/androidTest/java/com/android/periodpals/ui/alert` to mimic the `main` hierarchy.


### Improvements
 - As mentionned, make the UI responsive to the data coming from the ViewModel
 - Integrate the bottom navigation bar and top app bar once they're merged into main (see #21)
 - Consider renaming the files and classes to have "alert" always plural or always singular for consistency


### Steps before merge
lgtm: approving even if the file's locations are wrong, as @agonzalez-r's comment is already blocking the merge on those grounds

**Comment by lazarinibruno** [comment]
As noted by @agonzalez-r and @charliemangano, I moved

- `AlertList.kt` to `app/src/main/java/com/android/periodpals/ui/alert` 
- `AlertListScreenTest.kt` to `app/src/androidTest/java/com/android/periodpals/ui/alert`

**Review by agonzalez-r — APPROVED** [review]
LGTM

**Pull request merged**
