### PR TITLE
Fix/misc/auth map extract strings

### PR DESCRIPTION
**Pull request by taghizadlaura**
# Sign In, Sign Up, and Map texts in `strings.xml`

## Description  
This PR introduces string resources for the Sign In, Sign Up, and Map screens to improve readability and maintainability across the app. It ensures the content of these screens is easily managed through the `strings.xml` file. This update closes issue #334 (and part of #328).

## Changes  
- Added string resources for Sign In, Sign Up, and Map screens, including instructions, button text, toast messages, and other UI-related text.
- Updated the respective screens (`SignInScreen`, `SignUpScreen`, `MapScreen`) to use the newly added string resources, ensuring consistency and ease of maintenance.

#### Added  
- No files added.

#### Modified  
- `SignInScreen.kt` (updated to use string resources from `strings.xml`)
- `SignUpScreen.kt` (updated to use string resources from `strings.xml`)
- `MapScreen.kt` (updated to use string resources from `strings.xml`)
- `res/values/strings.xml` (new strings added for Sign In, Sign Up, and Map)

#### Removed  
- No files removed.

## Dependencies Added  
- No new dependencies added.

## Testing  
The Sign In, Sign Up, and Map screens have been updated to ensure the correct string resources are being used. Relevant tests have been adjusted to verify proper usage of the new resources.

### CODE REVIEW

**Review by lazarinibruno — COMMENTED** [review]
I verified that the text in the Sign In, Sign Up, and Map screens is correct. I noticed a small error: 

image

There should be a space between both sentences.

Moreover, I think it is best if you wait until I merge #303 because it introduces lots of changes in the Map screen.

**Comment by francelu** [comment]
> Moreover, I think it is best if you wait until I merge #303 because it introduces lots of changes in the Map screen.

@lazarinibruno  
I don't think it's a good idea, since we have to move on. In addition, I had requested changes which still have to be implemented / approved for which I won't have time before this evening.  

Moreover, during this morning's meeting, we said that this task will include a lot of changes. Hence, we will have to merge carefully anyway (before or after your other merge).

**Review by coaguila — APPROVED** [review]
LGTM

**Review by lazarinibruno — APPROVED** [review]
**_LGTM_**

**Pull request merged**
